 
// NEWS ACTIONS
export const GET_NEWS = "GET_NEWS"
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS"
export const GET_NEWS_FAIL = "GET_NEWS_FAIL"


// USER ACTIONS
export const GET_USERS = "GET_USERS"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAIL = "GET_USERS_FAIL"
export const ADD_USER = "ADD_USER"
export const EDIT_USER = "EDIT_USER"
export const UPDATE_USER = "UPDATE_USER"
export const DELETE_USER = "DELETE_ADDRESS"

// PRODUCT ACTIONS
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const RETRIEVE_PRODUCTS = "RETRIEVE_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_ALL_PRODUCTS = "DELETE_ALL_PRODUCTS";